name: Continuous Integration
 
on:
  push:
    branches:
      - main
 
jobs:
  Unit_Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Memasang paket metadata GitHub
        uses: actions/checkout@v3
      - name: Memasang paket Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Pasang semua paket NodeJS
        run: |
          npm install
      - name: Uji coba unit testing
        run: |
          rm -r dist
          npm run test
          npm run build
          date >> last_update.txt
          git config user.name fadzikri
          git config user.email 109416385+fadzikri@users.noreply.github.com
          git add -A
          git commit -m "Save"
          git push
