name: Continuous Integration
 
on:
  pull_request:
    branches:
      - main
 
jobs:
  Unit_Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Memasang paket metadata GitHub
        uses: actions/checkout@v3
      - name: Memasang paket Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Pasang semua paket NodeJS
        run: |
          npm install
      - name: Uji coba unit testing
        run: |
          npm run test
